#ifndef MEMBRANE_LAUNCHD_UNIT_H
# define MEMBRANE_LAUNCHD_UNIT_H

# include <string>

/*
 * Mega Phase D, PR D4: pure launchd LaunchAgent plist generation -- no
 * filesystem access, no launchctl invocation (that lives in
 * service_cmd.cpp, dispatched there via #ifdef __APPLE__) -- testable
 * with plain string assertions, exactly mirroring systemd_unit.h's own
 * split (that file's own top comment has the reasoning).
 *
 * launchd is macOS's per-user service manager (the direct analog of
 * systemd --user on Linux): a per-user LaunchAgent plist under
 * ~/Library/LaunchAgents/, loaded into the `gui/<uid>` domain via
 * `launchctl bootstrap` -- this project's own platform-abstraction
 * answer to "Section 4: never duplicate server/runtime logic" (server.h's
 * foreground membrane_server_run() is completely unchanged on either
 * platform; only how it gets supervised as a background service
 * differs).
 */

# define MEMBRANE_LAUNCHD_LABEL		"com.membrane.server"
# define MEMBRANE_LAUNCHD_MARKER	"Generated by `membrane service install` -- managed by MEMBRANE, safe to regenerate"

typedef struct s_membrane_launchd_options
{
	std::string	exec_path;		/* absolute path to the membrane binary */
	std::string	log_path;		/* StandardOutPath/StandardErrorPath;
								 * defaults applied by the generator if
								 * empty */
}	membrane_launchd_options_t;

/* A property-list (XML) equivalent of systemd_unit.h's own unit-file
 * generator. KeepAlive/SuccessfulExit=false is launchd's closest
 * analog to systemd's Restart=on-failure (restart only on a non-zero
 * exit, never on a clean exit); ThrottleInterval is launchd's own
 * restart-throttling knob (a minimum number of seconds between
 * relaunches) -- it bounds restart frequency the same way
 * Restart=on-failure + RestartSec=2 does, but the two mechanisms are
 * NOT identical (RestartSec is a fixed post-exit delay; ThrottleInterval
 * is a floor on how often launchd will relaunch at all) -- documented
 * honestly as a real behavioral difference in docs/macos-metal.md,
 * never claimed to be the same thing. RunAtLoad is deliberately false
 * (matching systemd_unit.h's own unit, which has no [Install]
 * WantedBy-at-boot-equivalent auto-start -- `membrane service start`
 * is the explicit, real way either platform's service actually starts,
 * matching product_onboarding's own "nothing starts without being
 * asked" policy). Ordinary per-user LaunchAgent, no root, no
 * elevated/System LaunchDaemon privileges of any kind.
 */
std::string	membrane_generate_launchd_plist(
				const membrane_launchd_options_t &opts);

/* $HOME/Library/LaunchAgents/com.membrane.server.plist -- macOS has no
 * XDG_CONFIG_HOME convention (unlike systemd_unit.h's Linux path
 * resolution), so this is simpler: always $HOME, no XDG fallback.
 * MEMBRANE_LAUNCHD_USER_DIR overrides the *directory* (tests/CI never
 * touch the real user's LaunchAgents directory), same override-env
 * pattern as MEMBRANE_SYSTEMD_USER_DIR. */
std::string	membrane_launchd_plist_path(void);

/* True iff `content` carries MEMBRANE_LAUNCHD_MARKER (as an XML
 * comment) -- used to refuse overwriting a same-named plist this
 * project did not create, same refuse-to-overwrite policy as
 * systemd_unit.h's membrane_unit_is_membrane_managed(). */
bool	membrane_launchd_plist_is_membrane_managed(const std::string &content);

#endif
