#ifndef MEMBRANE_SYSTEMD_UNIT_H
# define MEMBRANE_SYSTEMD_UNIT_H

# include <string>

/*
 * Mega Phase B, PR B1: pure systemd user-unit generation -- no
 * filesystem access, no systemctl invocation (that lives in
 * service_cmd.cpp) -- testable with plain string assertions.
 *
 * Prefers systemd --user over a custom fork/double-fork daemon
 * supervisor (Section 3 of the task) -- this project targets Linux
 * only (docs/install.md) and systemd --user is the standard per-user
 * service manager on every mainstream Linux distribution MEMBRANE
 * already supports.
 */

# define MEMBRANE_UNIT_NAME			"membrane.service"
# define MEMBRANE_UNIT_MARKER		"# Generated by `membrane service install` -- managed by MEMBRANE, safe to regenerate"

typedef struct s_membrane_unit_options
{
	std::string	exec_path;		/* absolute path to the membrane binary */
	std::string	description;	/* defaults applied by the generator if
								 * empty */
}	membrane_unit_options_t;

/* Section 7: binds only 127.0.0.1 by default (the unit itself does not
 * encode bind address/port -- those live in server_config.h's own
 * config file, read by `membrane serve` at startup, so changing them
 * never requires regenerating/reinstalling the unit); restarts on
 * unexpected failure with a bounded policy (Restart=on-failure,
 * RestartSec=2 -- never an aggressive/immediate restart loop); stops
 * cleanly on SIGTERM (systemd's own default KillSignal, unchanged --
 * membrane serve's existing SIGTERM handler already exits cleanly, see
 * server.cpp); ordinary user permissions, no root, no elevated
 * capabilities of any kind; no Requires=network-online.target (this is
 * a loopback-only local service, Section 7: "no external network
 * requirement"). */
std::string	membrane_generate_unit_file(const membrane_unit_options_t &opts);

/* Section 5: $XDG_CONFIG_HOME/systemd/user/membrane.service, falling
 * back to $HOME/.config/systemd/user/membrane.service -- never
 * /etc/systemd/system or any root-owned location.
 * MEMBRANE_SYSTEMD_USER_DIR overrides the *directory* (tests/CI never
 * touch the real user's systemd config). */
std::string	membrane_unit_file_path(void);

/* Section 12: true iff `content` carries MEMBRANE_UNIT_MARKER as one of
 * its lines -- used to refuse overwriting a same-named unit this
 * project did not create. */
bool	membrane_unit_is_membrane_managed(const std::string &content);

#endif
