#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#ifndef _WIN32
# include <unistd.h>
#endif

#include <httplib.h>
#include <nlohmann/json.hpp>

#include "runtime_adapter.h"
#include "runtime_cmd.h"
#include "runtime_capabilities.h"
#include "runtime_ollama.h"
#include "product_cli.h"
#include "test_helpers.h"

using json = nlohmann::json;

/*
 * Milestone H2: the read-only Ollama adapter's own tests. No Ollama
 * install is needed or used: a real in-process httplib::Server on an
 * ephemeral 127.0.0.1 port serves deterministic fixtures shaped exactly
 * like ollama/ollama v0.34.3's documented responses (docs/openapi.yaml),
 * and MEMBRANE_OLLAMA_ENDPOINT is always pinned to that mock or to a
 * closed port -- a real daemon on the test host is never contacted.
 *
 * The mock logs EVERY request it receives (set_logger fires for matched
 * and unmatched routes alike), which is what the read-only / no-
 * inference tests assert against.
 */

static const char	*g_version_fixture = "{\"version\":\"0.34.3\"}";

static const char	*g_tags_fixture = R"({
  "models": [
    {
      "name": "qwen2.5:7b",
      "model": "qwen2.5:7b",
      "modified_at": "2026-09-01T10:00:00.000000000+03:00",
      "size": 4683087332,
      "digest": "845dbda0ea48ed749caafd9e6037047aa19acfcfd82e704d7ca97d631a0b697e",
      "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "qwen2",
        "families": ["qwen2"],
        "parameter_size": "7.6B",
        "quantization_level": "Q4_K_M",
        "context_length": 32768
      },
      "capabilities": ["completion", "tools"]
    },
    {
      "name": "llama3.2:3b",
      "model": "llama3.2:3b",
      "modified_at": "2026-08-20T09:00:00.000000000+03:00",
      "size": 2019393189,
      "digest": "a80c4f17acd55265feec403c7aef86be0c25983ab279d83f3bcd3abbcb5b8b72",
      "details": {
        "format": "gguf",
        "family": "llama",
        "families": ["llama"],
        "parameter_size": "3.2B",
        "quantization_level": "Q4_K_M"
      }
    },
    {
      "name": "gpt-oss:20b-cloud",
      "model": "gpt-oss:20b-cloud",
      "remote_model": "gpt-oss:20b",
      "remote_host": "https://ollama.com:443",
      "modified_at": "2026-08-01T09:00:00.000000000+03:00",
      "size": 384,
      "digest": "875d8a8b2f2b9d1b41f2ab9c3a1f3d2e0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a59",
      "details": {"format": "", "family": "", "families": null,
        "parameter_size": "", "quantization_level": ""}
    }
  ]
})";

static const char	*g_show_fixture = R"({
  "license": "Apache License\nVersion 2.0, January 2004",
  "modelfile": "# Modelfile generated by \"ollama show\"\nFROM /x\n",
  "parameters": "stop                           \"<|im_start|>\"\nstop                           \"<|im_end|>\"",
  "template": "{{ if .System }}<|im_start|>system\n{{ .System }}<|im_end|>{{ end }}",
  "details": {
    "parent_model": "",
    "format": "gguf",
    "family": "qwen2",
    "families": ["qwen2"],
    "parameter_size": "7.6B",
    "quantization_level": "Q4_K_M"
  },
  "model_info": {
    "general.architecture": "qwen2",
    "general.file_type": 15,
    "general.parameter_count": 7615616512,
    "general.quantization_version": 2,
    "qwen2.attention.head_count": 28,
    "qwen2.attention.head_count_kv": 4,
    "qwen2.block_count": 28,
    "qwen2.context_length": 32768,
    "qwen2.embedding_length": 3584,
    "tokenizer.ggml.tokens": null
  },
  "capabilities": ["completion", "tools"],
  "modified_at": "2026-09-01T10:00:00.000000000+03:00"
})";

/* ---------------------------------------------------------------- */
/* Mock Ollama server                                               */
/* ---------------------------------------------------------------- */

typedef struct s_route_reply
{
	int			status;
	std::string	body;
	int			delay_ms;
}	route_reply_t;

static httplib::Server			*g_mock;
static std::thread				*g_mock_thread;
static int						g_mock_port;
static std::mutex				g_mock_mutex;
static std::vector<std::string>	g_mock_log;
static route_reply_t			g_version_reply;
static route_reply_t			g_tags_reply;
static route_reply_t			g_show_reply;
static std::string				g_last_show_body;

static void	reset_mock_replies(void)
{
	std::lock_guard<std::mutex>	lock(g_mock_mutex);

	g_version_reply = {200, g_version_fixture, 0};
	g_tags_reply = {200, g_tags_fixture, 0};
	g_show_reply = {200, g_show_fixture, 0};
	g_mock_log.clear();
	g_last_show_body.clear();
}

static void	reply(const route_reply_t &r, httplib::Response &res)
{
	if (r.delay_ms > 0)
		std::this_thread::sleep_for(std::chrono::milliseconds(r.delay_ms));
	res.status = r.status;
	res.set_content(r.body, "application/json; charset=utf-8");
}

static void	trap(const httplib::Request &, httplib::Response &res)
{
	/* Never expected to be reached -- the log assertion catches it. */
	res.status = 500;
	res.set_content("{\"error\":\"trap route hit\"}", "application/json");
}

static void	start_mock_server(void)
{
	reset_mock_replies();
	g_mock = new httplib::Server();
	g_mock->set_logger([](const httplib::Request &req,
			const httplib::Response &)
	{
		std::lock_guard<std::mutex>	lock(g_mock_mutex);

		g_mock_log.push_back(req.method + " " + req.path);
	});
	g_mock->Get("/api/version", [](const httplib::Request &,
			httplib::Response &res)
	{
		route_reply_t	r;

		{
			std::lock_guard<std::mutex>	lock(g_mock_mutex);
			r = g_version_reply;
		}
		reply(r, res);
	});
	g_mock->Get("/api/tags", [](const httplib::Request &,
			httplib::Response &res)
	{
		route_reply_t	r;

		{
			std::lock_guard<std::mutex>	lock(g_mock_mutex);
			r = g_tags_reply;
		}
		reply(r, res);
	});
	g_mock->Post("/api/show", [](const httplib::Request &req,
			httplib::Response &res)
	{
		route_reply_t	r;

		{
			std::lock_guard<std::mutex>	lock(g_mock_mutex);
			r = g_show_reply;
			g_last_show_body = req.body;
		}
		reply(r, res);
	});
	/* Every mutating / inference / cloud route Ollama v0.34.3 registers
	 * that this adapter must never reach. */
	for (const char *p : {"/api/generate", "/api/chat", "/api/embed",
			"/api/embeddings", "/api/pull", "/api/push", "/api/create",
			"/api/copy", "/api/me", "/api/signout",
			"/v1/chat/completions", "/v1/completions", "/v1/embeddings",
			"/v1/responses", "/v1/messages"})
		g_mock->Post(p, trap);
	g_mock->Delete("/api/delete", trap);
	g_mock->Get("/api/ps", trap);
	g_mock->Get("/api/status", trap);
	g_mock->Get("/v1/models", trap);
	g_mock_port = g_mock->bind_to_any_port("127.0.0.1");
	TEST_ASSERT(g_mock_port > 0, "mock server bound an ephemeral port");
	g_mock_thread = new std::thread([]() { g_mock->listen_after_bind(); });

	int	attempts = 0;

	while (!g_mock->is_running() && attempts < 100)
	{
		std::this_thread::sleep_for(std::chrono::milliseconds(20));
		attempts++;
	}
	TEST_ASSERT(g_mock->is_running(), "mock server became ready");
}

static void	stop_mock_server(void)
{
	g_mock->stop();
	g_mock_thread->join();
	delete g_mock_thread;
	delete g_mock;
	g_mock = NULL;
	g_mock_thread = NULL;
}

static std::string	mock_url(void)
{
	return ("http://127.0.0.1:" + std::to_string(g_mock_port));
}

static void	use_mock_endpoint(void)
{
	setenv(MEMBRANE_OLLAMA_ENDPOINT_ENV, mock_url().c_str(), 1);
}

static void	use_closed_endpoint(void)
{
	setenv(MEMBRANE_OLLAMA_ENDPOINT_ENV, "http://127.0.0.1:1", 1);
}

static std::vector<std::string>	mock_log(void)
{
	std::lock_guard<std::mutex>	lock(g_mock_mutex);

	return (g_mock_log);
}

static void	set_reply(route_reply_t *slot, int status, const std::string &body,
				int delay_ms = 0)
{
	std::lock_guard<std::mutex>	lock(g_mock_mutex);

	*slot = {status, body, delay_ms};
}

/* ---------------------------------------------------------------- */
/* stdout/stderr capture around the real CLI dispatch               */
/* ---------------------------------------------------------------- */

static std::string	read_and_remove(const char *path)
{
	FILE		*f = fopen(path, "r");
	std::string	out;
	char		buf[4096];
	size_t		n;

	TEST_ASSERT(f != NULL, "could reopen a capture temp file");
	while ((n = fread(buf, 1, sizeof(buf), f)) > 0)
		out.append(buf, n);
	fclose(f);
	remove(path);
	return (out);
}

static std::string	run_cli(const std::vector<std::string> &args,
				bool want_json, int *out_rc, std::string *out_stderr = NULL)
{
	char	out_tmpl[] = "/tmp/membrane-runtime-ollama-out-XXXXXX";
	char	err_tmpl[] = "/tmp/membrane-runtime-ollama-err-XXXXXX";
	int		out_fd = mkstemp(out_tmpl);
	int		err_fd = mkstemp(err_tmpl);
	int		saved_out;
	int		saved_err;

	TEST_ASSERT(out_fd >= 0 && err_fd >= 0, "capture temp files created");
	fflush(stdout);
	fflush(stderr);
	saved_out = dup(STDOUT_FILENO);
	saved_err = dup(STDERR_FILENO);
	dup2(out_fd, STDOUT_FILENO);
	dup2(err_fd, STDERR_FILENO);
	close(out_fd);
	close(err_fd);
	*out_rc = membrane_runtime_cmd_dispatch(args, want_json);
	fflush(stdout);
	fflush(stderr);
	dup2(saved_out, STDOUT_FILENO);
	dup2(saved_err, STDERR_FILENO);
	close(saved_out);
	close(saved_err);

	std::string	err_text = read_and_remove(err_tmpl);

	if (out_stderr != NULL)
		*out_stderr = err_text;
	return (read_and_remove(out_tmpl));
}

static bool	contains(const std::string &hay, const std::string &needle)
{
	return (hay.find(needle) != std::string::npos);
}

/* ---------------------------------------------------------------- */
/* A: Ollama unavailable                                            */
/* ---------------------------------------------------------------- */

static void	test_unavailable_descriptor(void)
{
	membrane_runtime_descriptor_t	d;

	use_closed_endpoint();
	membrane_ollama_describe(&d);
	TEST_ASSERT(std::string(d.id) == MEMBRANE_RUNTIME_ID_OLLAMA,
		"an unreachable ollama is still a known runtime");
	TEST_ASSERT(d.type == MEMBRANE_RUNTIME_TYPE_EXTERNAL, "type external");
	TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_UNAVAILABLE,
		"unreachable -> unavailable");
	TEST_ASSERT(d.health == MEMBRANE_RUNTIME_HEALTH_UNREACHABLE,
		"unreachable -> health unreachable");
	TEST_ASSERT(!d.version_known, "no version is fabricated");
	TEST_ASSERT(d.endpoint_known
		&& std::string(d.endpoint) == "http://127.0.0.1:1",
		"the probed endpoint is still reported");
	TEST_ASSERT(std::string(d.unavailable_reason)
		== "Ollama API is not reachable.", "a plain, human reason");
}

static void	test_unavailable_cli_has_no_socket_error(void)
{
	int			rc;
	std::string	err;
	std::string	out;

	use_closed_endpoint();
	out = run_cli({"list"}, false, &rc, &err);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS, "list exits 0 even when "
		"ollama is down");
	TEST_ASSERT(contains(out, "ollama") && contains(out, "unavailable"),
		"list shows ollama as unavailable");
	out = run_cli({"inspect", "ollama"}, false, &rc, &err);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS, "inspect of an unavailable "
		"ollama still succeeds (describes the adapter)");
	TEST_ASSERT(contains(out, "Status: unavailable")
		&& contains(out, "Endpoint: http://127.0.0.1:1")
		&& contains(out, "Reason\n  Ollama API is not reachable."),
		"inspect shows status, endpoint and a Reason block");
	TEST_ASSERT(!contains(out + err, "Connection") && !contains(out + err,
		"errno") && !contains(out + err, "refused"),
		"no low-level socket error text is printed");
	out = run_cli({"models", "ollama"}, true, &rc, &err);
	TEST_ASSERT(rc == MEMBRANE_EXIT_RUNTIME_ERROR, "models on a down "
		"ollama is a RUNTIME_ERROR");
	TEST_ASSERT(json::parse(out)["error"]["code"]
		== MEMBRANE_RUNTIME_ERR_UNAVAILABLE, "structured unavailable code");
}

/* ---------------------------------------------------------------- */
/* B: healthy + version                                             */
/* ---------------------------------------------------------------- */

static void	test_healthy_version(void)
{
	membrane_runtime_descriptor_t	d;
	json							j;
	std::string						err;

	reset_mock_replies();
	use_mock_endpoint();
	membrane_ollama_describe(&d);
	TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_AVAILABLE,
		"reachable + valid version -> available");
	TEST_ASSERT(d.health == MEMBRANE_RUNTIME_HEALTH_HEALTHY, "healthy");
	TEST_ASSERT(d.version_known && std::string(d.version) == "0.34.3",
		"version parsed from GET /api/version");
	TEST_ASSERT(d.version_provenance == MEMBRANE_CAPABILITY_PROVENANCE_API_PROBE,
		"version provenance is api_probe");
	TEST_ASSERT(d.execution_mode == MEMBRANE_RUNTIME_EXEC_LOCAL_EXTERNAL,
		"a loopback endpoint is local_external");
	TEST_ASSERT(std::string(d.endpoint) == mock_url(), "endpoint echoed");
	TEST_ASSERT(membrane_runtime_inspect_json("ollama", &j, &err),
		"inspect --json succeeds");
	TEST_ASSERT(j["runtime"]["status"] == "available"
		&& j["runtime"]["health"] == "healthy"
		&& j["runtime"]["version"] == "0.34.3"
		&& j["runtime"]["version_provenance"] == "api_probe"
		&& j["runtime"]["unavailable_reason"].is_null(),
		"inspect JSON carries status/health/version/provenance");
}

static void	test_list_shows_version_when_reachable(void)
{
	int			rc;
	std::string	out;
	json		j;

	reset_mock_replies();
	use_mock_endpoint();
	out = run_cli({"list"}, false, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS, "list exits 0");
	TEST_ASSERT(contains(out, "ollama") && contains(out, "external")
		&& contains(out, "0.34.3"), "list shows ollama external + version");
	j = membrane_runtime_list_json();
	TEST_ASSERT(j["runtimes"].size() == 2, "exactly native + ollama");
	TEST_ASSERT(j["runtimes"][1]["status"] == "available", "ollama available");
	for (const auto &r : j["runtimes"])
		TEST_ASSERT(r["id"] != MEMBRANE_RUNTIME_ID_VLLM, "vllm is not listed");
}

/* ---------------------------------------------------------------- */
/* C: model list                                                    */
/* ---------------------------------------------------------------- */

static void	test_models_parsed(void)
{
	json						j;
	json						again;
	membrane_runtime_error_t	err;

	reset_mock_replies();
	use_mock_endpoint();
	TEST_ASSERT(membrane_runtime_models_json("ollama", &j, &err),
		"models --json succeeds");
	TEST_ASSERT(j["runtime_id"] == "ollama", "runtime_id");
	TEST_ASSERT(j["models"].size() == 3, "all 3 fixture models parsed");

	const json	&q = j["models"][0];

	TEST_ASSERT(q["runtime_model_id"] == "qwen2.5:7b"
		&& q["display_name"] == "qwen2.5:7b", "name/model id");
	TEST_ASSERT(q["size_bytes"] == 4683087332ULL, "size_bytes");
	TEST_ASSERT(q["digest"].get<std::string>().size() == 64, "digest");
	TEST_ASSERT(q["family"] == "qwen2" && q["format"] == "gguf"
		&& q["parameter_size"] == "7.6B" && q["quantization"] == "Q4_K_M",
		"details mapped verbatim");
	TEST_ASSERT(q["context_length"] == 32768, "context_length when exposed");
	TEST_ASSERT(q["modified_at"] == "2026-09-01T10:00:00.000000000+03:00",
		"modified_at verbatim");
	TEST_ASSERT(q["runtime_capabilities"] == json({"completion", "tools"}),
		"model capabilities as reported");
	TEST_ASSERT(q["provenance"] == "api_probe" && q["remote"] == false,
		"provenance + local");
	TEST_ASSERT(j["models"][1]["context_length"].is_null(),
		"context_length not fabricated when absent");
	TEST_ASSERT(j["models"][1]["runtime_capabilities"].empty(),
		"no capabilities invented when absent");
	TEST_ASSERT(j["models"][2]["remote"] == true
		&& j["models"][2]["remote_host"] == "https://ollama.com:443"
		&& j["models"][2]["family"].is_null(),
		"remote stub flagged; empty strings become null");
	TEST_ASSERT(membrane_runtime_models_json("ollama", &again, &err)
		&& again.dump() == j.dump(), "deterministic JSON");
}

static void	test_models_human(void)
{
	int			rc;
	std::string	out;

	reset_mock_replies();
	use_mock_endpoint();
	out = run_cli({"models", "ollama"}, false, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS, "models exits 0");
	TEST_ASSERT(contains(out, "NAME") && contains(out, "SIZE")
		&& contains(out, "FAMILY"), "table header");
	TEST_ASSERT(contains(out, "qwen2.5:7b") && contains(out, "4.7 GB")
		&& contains(out, "qwen2") && contains(out, "llama3.2:3b")
		&& contains(out, "2.0 GB"), "rows with sizes and family");
	TEST_ASSERT(contains(out, "remote stubs") || contains(out, "remote stub"),
		"remote stub footnote");
	set_reply(&g_tags_reply, 200, "{\"models\":[]}");
	out = run_cli({"models", "ollama"}, false, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS && contains(out, "no local "
		"models"), "empty inventory is a clean success");
}

/* ---------------------------------------------------------------- */
/* D: malformed / incompatible version                              */
/* ---------------------------------------------------------------- */

static void	test_malformed_version(void)
{
	membrane_runtime_descriptor_t	d;
	std::string						big(70 * 1024, 'x');

	use_mock_endpoint();
	for (const char *bad : {"not json", "{\"version\":5}", "[]",
			"{\"version\":\"\"}", "{\"version\":\"0.1\\n; rm\"}"})
	{
		reset_mock_replies();
		set_reply(&g_version_reply, 200, bad);
		membrane_ollama_describe(&d);
		TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_UNKNOWN,
			"malformed version -> availability unknown");
		TEST_ASSERT(d.health == MEMBRANE_RUNTIME_HEALTH_UNKNOWN,
			"malformed version -> health unknown");
		TEST_ASSERT(!d.version_known, "no version fabricated");
		TEST_ASSERT(contains(d.unavailable_reason, "malformed"),
			"reason says malformed");
	}
	set_reply(&g_version_reply, 404, "404 page not found");
	membrane_ollama_describe(&d);
	TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_UNAVAILABLE
		&& d.health == MEMBRANE_RUNTIME_HEALTH_INCOMPATIBLE,
		"non-2xx on /api/version -> reachable but incompatible");
	TEST_ASSERT(contains(d.unavailable_reason, "HTTP 404"),
		"reason names the status");
	set_reply(&g_version_reply, 200, "{\"version\":\"" + big + "\"}");
	membrane_ollama_describe(&d);
	TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_UNKNOWN
		&& contains(d.unavailable_reason, "size limit"),
		"an oversized response is bounded, not buffered");
}

static void	test_version_timeout_is_bounded(void)
{
	membrane_runtime_descriptor_t	d;
	auto							start = std::chrono::steady_clock::now();
	long							ms;

	reset_mock_replies();
	use_mock_endpoint();
	set_reply(&g_version_reply, 200, g_version_fixture, 3500);
	membrane_ollama_describe(&d);
	ms = (long)std::chrono::duration_cast<std::chrono::milliseconds>(
		std::chrono::steady_clock::now() - start).count();
	TEST_ASSERT(d.health == MEMBRANE_RUNTIME_HEALTH_UNREACHABLE,
		"a hung daemon is reported unreachable");
	TEST_ASSERT(ms < 3400, "the version probe gives up within its bound");
	/* Let the mock's sleeping handler finish so its log line cannot leak
	 * into a later test's request log. */
	std::this_thread::sleep_for(std::chrono::milliseconds(3500 - ms + 300));
	reset_mock_replies();
}

/* ---------------------------------------------------------------- */
/* E: malformed model list                                          */
/* ---------------------------------------------------------------- */

static void	test_malformed_models(void)
{
	json						j;
	membrane_runtime_error_t	err;
	int							rc;
	std::string					out;

	use_mock_endpoint();
	for (const char *bad : {"{", "{}", "{\"models\":\"x\"}",
			"{\"models\":[1]}", "{\"models\":[{\"size\":1}]}"})
	{
		reset_mock_replies();
		set_reply(&g_tags_reply, 200, bad);
		TEST_ASSERT(!membrane_runtime_models_json("ollama", &j, &err),
			"malformed model list is rejected");
		TEST_ASSERT(err.code == MEMBRANE_RUNTIME_ERR_MALFORMED,
			"code MALFORMED_RESPONSE");
	}
	set_reply(&g_tags_reply, 500, "{\"error\":\"disk exploded\"}");
	TEST_ASSERT(!membrane_runtime_models_json("ollama", &j, &err)
		&& err.code == MEMBRANE_RUNTIME_ERR_HTTP
		&& contains(err.message, "HTTP 500")
		&& contains(err.message, "disk exploded"),
		"non-2xx surfaces status + Ollama's own error text");
	out = run_cli({"models", "ollama"}, false, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_RUNTIME_ERROR && out.empty(),
		"human mode: clean RUNTIME_ERROR, nothing on stdout");
	reset_mock_replies();
}

/* ---------------------------------------------------------------- */
/* F: model metadata / show                                         */
/* ---------------------------------------------------------------- */

static void	test_model_inspect(void)
{
	json						j;
	membrane_runtime_error_t	err;
	int							rc;
	std::string					out;

	reset_mock_replies();
	use_mock_endpoint();
	TEST_ASSERT(membrane_runtime_model_inspect_json("ollama", "qwen2.5:7b",
		&j, &err), "model inspect succeeds");
	TEST_ASSERT(json::parse(g_last_show_body) == json({{"model",
		"qwen2.5:7b"}}), "request body is exactly {\"model\": NAME} (no "
		"verbose, no options)");

	const json	&m = j["model"];

	TEST_ASSERT(m["runtime_model_id"] == "qwen2.5:7b", "identity");
	TEST_ASSERT(m["architecture"] == "qwen2", "architecture");
	TEST_ASSERT(m["parameter_size"] == "7.6B"
		&& m["parameter_count"] == 7615616512ULL, "parameter size + count");
	TEST_ASSERT(m["quantization"] == "Q4_K_M", "quantization");
	TEST_ASSERT(m["context_length"] == 32768,
		"context length from model_info.<arch>.context_length");
	TEST_ASSERT(m["has_template"] == true && m["has_license"] == true
		&& m["has_system"] == false, "template/license presence only");
	TEST_ASSERT(contains(m["parameters"].get<std::string>(), "<|im_end|>"),
		"runtime default parameters");
	TEST_ASSERT(m["size_bytes"].is_null() && m["digest"].is_null(),
		"/api/show does not report size/digest -- not fabricated");
	out = run_cli({"model", "inspect", "ollama", "qwen2.5:7b"}, false, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS, "human model inspect exits 0");
	TEST_ASSERT(contains(out, "Architecture: qwen2")
		&& contains(out, "Context length (model maximum): 32768")
		&& contains(out, "Template: present"), "human metadata");
	TEST_ASSERT(!contains(out, "<|im_start|>system")
		&& !contains(out, "Apache License"),
		"template/license bodies are never dumped");

	set_reply(&g_show_reply, 404,
		"{\"error\":\"model 'nope' not found\"}");
	out = run_cli({"model", "inspect", "ollama", "nope"}, true, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_MODEL_ERROR, "missing model -> "
		"MODEL_ERROR");
	TEST_ASSERT(json::parse(out)["error"]["code"]
		== MEMBRANE_RUNTIME_ERR_MODEL_NOT_FOUND, "MODEL_NOT_FOUND code");
	set_reply(&g_show_reply, 200, "[1,2");
	TEST_ASSERT(!membrane_runtime_model_inspect_json("ollama", "x", &j, &err)
		&& err.code == MEMBRANE_RUNTIME_ERR_MALFORMED,
		"malformed show -> MALFORMED_RESPONSE");
	reset_mock_replies();
}

static void	test_cloud_refs_refused_without_request(void)
{
	json						j;
	membrane_runtime_error_t	err;

	reset_mock_replies();
	use_mock_endpoint();
	TEST_ASSERT(membrane_ollama_is_cloud_model_ref("gpt-oss:20b:cloud")
		&& membrane_ollama_is_cloud_model_ref("gpt-oss:20b-cloud")
		&& membrane_ollama_is_cloud_model_ref("kimi:CLOUD")
		&& !membrane_ollama_is_cloud_model_ref("qwen2.5:7b")
		&& !membrane_ollama_is_cloud_model_ref("cloudy:latest")
		&& !membrane_ollama_is_cloud_model_ref("host:5000/x-cloud"),
		"cloud-ref detection mirrors Ollama's modelref suffix rule");
	for (const char *name : {"gpt-oss:20b-cloud", "x:cloud"})
	{
		TEST_ASSERT(!membrane_runtime_model_inspect_json("ollama", name, &j,
			&err) && err.code == MEMBRANE_RUNTIME_ERR_CLOUD_REFUSED,
			"cloud model refs are refused");
	}
	TEST_ASSERT(!membrane_runtime_model_inspect_json("ollama", "a b", &j,
		&err) && err.code == MEMBRANE_RUNTIME_ERR_INVALID_MODEL,
		"whitespace in a model name is rejected locally");
	TEST_ASSERT(mock_log().empty(), "refused names never reach the daemon");
}

/* ---------------------------------------------------------------- */
/* G: capability matrix                                             */
/* ---------------------------------------------------------------- */

static void	test_capability_matrix(void)
{
	membrane_runtime_capabilities_t	c;
	json							j;
	std::string						err;

	membrane_ollama_capabilities(&c);
	TEST_ASSERT(c.model_enumeration == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.model_metadata == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.model_switch == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.model_load_unload == MEMBRANE_CAPABILITY_PARTIAL,
		"model lifecycle");
	TEST_ASSERT(c.context_control == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.gpu_layer_control == MEMBRANE_CAPABILITY_PARTIAL
		&& c.quant_variant_control == MEMBRANE_CAPABILITY_PARTIAL
		&& c.kv_precision_control == MEMBRANE_CAPABILITY_UNSUPPORTED
		&& c.kv_placement_control == MEMBRANE_CAPABILITY_UNSUPPORTED
		&& c.concurrency_control == MEMBRANE_CAPABILITY_UNSUPPORTED
		&& c.device_selection == MEMBRANE_CAPABILITY_UNKNOWN
		&& c.memory_headroom_telemetry == MEMBRANE_CAPABILITY_UNSUPPORTED,
		"planning control: server-start env knobs are NOT API controls");
	TEST_ASSERT(c.chat_completions == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.streaming == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.cancellation == MEMBRANE_CAPABILITY_UNKNOWN, "inference");
	TEST_ASSERT(c.current_model == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.active_context == MEMBRANE_CAPABILITY_SUPPORTED
		&& c.ram_usage == MEMBRANE_CAPABILITY_PARTIAL
		&& c.vram_usage == MEMBRANE_CAPABILITY_PARTIAL
		&& c.kv_cache_usage == MEMBRANE_CAPABILITY_UNSUPPORTED
		&& c.loaded_model_memory == MEMBRANE_CAPABILITY_PARTIAL,
		"observability");
	TEST_ASSERT(c.live_kv_migration == MEMBRANE_CAPABILITY_UNSUPPORTED
		&& c.dynamic_reconfiguration == MEMBRANE_CAPABILITY_UNSUPPORTED,
		"advanced");
	use_closed_endpoint();
	TEST_ASSERT(membrane_runtime_inspect_json("ollama", &j, &err),
		"inspect works while unavailable");
	TEST_ASSERT(j["runtime"]["capability_provenance"] == "static_contract"
		&& j["runtime"]["capabilities"]["kv_precision_control"]
			== "unsupported", "matrix is reported even when unavailable, "
		"as a static contract");
}

/* ---------------------------------------------------------------- */
/* H: endpoint override                                             */
/* ---------------------------------------------------------------- */

static void	test_endpoint_parsing(void)
{
	membrane_ollama_endpoint_t	e;

	e = membrane_ollama_parse_endpoint(MEMBRANE_OLLAMA_DEFAULT_ENDPOINT);
	TEST_ASSERT(e.ok && e.host == "127.0.0.1" && e.port == 11434
		&& e.loopback, "documented default is loopback 11434");
	e = membrane_ollama_parse_endpoint("http://localhost/");
	TEST_ASSERT(e.ok && e.port == 11434 && e.loopback
		&& e.url == "http://localhost:11434", "default port + normalize");
	e = membrane_ollama_parse_endpoint("http://[::1]:8080");
	TEST_ASSERT(e.ok && e.host == "::1" && e.port == 8080 && e.loopback
		&& e.url == "http://[::1]:8080", "bracketed IPv6 loopback");
	e = membrane_ollama_parse_endpoint("http://192.168.1.20:11434");
	TEST_ASSERT(e.ok && !e.loopback, "an explicit LAN host is NOT loopback");
	e = membrane_ollama_parse_endpoint("http://0.0.0.0:11434");
	TEST_ASSERT(e.ok && !e.loopback, "0.0.0.0 is not treated as loopback");
	for (const char *bad : {"https://127.0.0.1:11434", "127.0.0.1:11434",
			"ftp://x", "http://user:pw@127.0.0.1:11434",
			"http://127.0.0.1:11434/api", "http://127.0.0.1:0",
			"http://127.0.0.1:99999", "http://127.0.0.1:", "http://",
			"http://::1:11434", "http://127.0.0.1:11434?x=1"})
	{
		e = membrane_ollama_parse_endpoint(bad);
		TEST_ASSERT(!e.ok && !e.error.empty(), "invalid endpoint rejected");
	}
}

static void	test_endpoint_override(void)
{
	membrane_runtime_descriptor_t	d;
	membrane_ollama_endpoint_t		e;

	unsetenv(MEMBRANE_OLLAMA_ENDPOINT_ENV);
	e = membrane_ollama_resolve_endpoint();
	TEST_ASSERT(e.ok && !e.from_env && e.url == "http://127.0.0.1:11434",
		"unset -> documented loopback default");
	reset_mock_replies();
	use_mock_endpoint();
	e = membrane_ollama_resolve_endpoint();
	TEST_ASSERT(e.ok && e.from_env && e.port == g_mock_port,
		"MEMBRANE_OLLAMA_ENDPOINT overrides the default");
	membrane_ollama_describe(&d);
	TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_AVAILABLE,
		"custom local fixture endpoint works");
	TEST_ASSERT(mock_log() == std::vector<std::string>({"GET /api/version"}),
		"discovery is exactly one GET /api/version");
	setenv(MEMBRANE_OLLAMA_ENDPOINT_ENV, "https://ollama.com", 1);
	reset_mock_replies();
	membrane_ollama_describe(&d);
	TEST_ASSERT(d.availability == MEMBRANE_RUNTIME_AVAILABILITY_UNAVAILABLE
		&& d.health == MEMBRANE_RUNTIME_HEALTH_NOT_PROBED
		&& !d.endpoint_known
		&& contains(d.unavailable_reason, "MEMBRANE_OLLAMA_ENDPOINT is "
			"invalid"), "invalid override: explained, nothing probed");
}

/* ---------------------------------------------------------------- */
/* I + J: read-only, no inference                                   */
/* ---------------------------------------------------------------- */

static std::string	make_temp_dir(void)
{
	char	tmpl[] = "/tmp/membrane-runtime-ollama-test-XXXXXX";
	char	*dir = mkdtemp(tmpl);

	TEST_ASSERT(dir != NULL, "mkdtemp succeeded");
	return (std::string(dir));
}

static void	test_read_only_and_no_inference(void)
{
	std::string	dir = make_temp_dir();
	std::string	cmd;
	int			rc;

	setenv("MEMBRANE_MODELS_PATH", (dir + "/models.json").c_str(), 1);
	setenv("MEMBRANE_SERVER_CONFIG_PATH", (dir + "/server.json").c_str(), 1);
	setenv("MEMBRANE_SYSTEMD_USER_DIR", dir.c_str(), 1);
	reset_mock_replies();
	use_mock_endpoint();
	run_cli({"list"}, false, &rc);
	run_cli({"list"}, true, &rc);
	run_cli({"inspect", "ollama"}, false, &rc);
	run_cli({"inspect", "ollama"}, true, &rc);
	run_cli({"models", "ollama"}, false, &rc);
	run_cli({"models", "ollama"}, true, &rc);
	run_cli({"model", "inspect", "ollama", "qwen2.5:7b"}, false, &rc);
	run_cli({"model", "inspect", "ollama", "qwen2.5:7b"}, true, &rc);
	run_cli({"model", "inspect", "ollama", "gpt-oss:20b-cloud"}, true, &rc);

	std::vector<std::string>	log = mock_log();

	TEST_ASSERT(!log.empty(), "the commands did reach the mock");
	for (const auto &line : log)
	{
		size_t		sp = line.find(' ');
		std::string	method = line.substr(0, sp);
		std::string	path = line.substr(sp + 1);

		TEST_ASSERT(membrane_ollama_request_allowed(method, path),
			"every request the daemon saw is on the read-only allowlist");
		TEST_ASSERT(path != "/api/generate" && path != "/api/chat"
			&& path.compare(0, 4, "/v1/") != 0,
			"no inference request was ever sent");
		TEST_ASSERT(path != "/api/pull" && path != "/api/delete"
			&& path != "/api/create" && path != "/api/copy"
			&& path != "/api/push", "no mutating request was ever sent");
	}
	cmd = "[ -z \"$(ls -A '" + dir + "' 2>/dev/null)\" ]";
	TEST_ASSERT(system(cmd.c_str()) == 0, "no registry/config/service file "
		"was created");
	cmd = "rm -rf '" + dir + "'";
	if (system(cmd.c_str()) != 0)
		fprintf(stderr, "warning: cleanup of %s failed\n", dir.c_str());
	unsetenv("MEMBRANE_MODELS_PATH");
	unsetenv("MEMBRANE_SERVER_CONFIG_PATH");
	unsetenv("MEMBRANE_SYSTEMD_USER_DIR");
}

static void	test_allowlist(void)
{
	TEST_ASSERT(membrane_ollama_request_allowed("GET", "/api/version")
		&& membrane_ollama_request_allowed("GET", "/api/tags")
		&& membrane_ollama_request_allowed("POST", "/api/show"),
		"the 3 read-only calls are allowed");
	for (const char *p : {"/api/generate", "/api/chat", "/api/pull",
			"/api/push", "/api/create", "/api/copy", "/api/embed",
			"/api/blobs/sha256:x", "/v1/chat/completions", "/api/me",
			"/api/show/../pull"})
		TEST_ASSERT(!membrane_ollama_request_allowed("POST", p),
			"mutating/inference/cloud POSTs are refused");
	TEST_ASSERT(!membrane_ollama_request_allowed("DELETE", "/api/delete")
		&& !membrane_ollama_request_allowed("GET", "/api/ps")
		&& !membrane_ollama_request_allowed("GET", "/api/show")
		&& !membrane_ollama_request_allowed("POST", "/api/tags"),
		"exact method+path match only");
}

/* ---------------------------------------------------------------- */
/* K: membrane-native regression                                    */
/* ---------------------------------------------------------------- */

static void	test_native_unchanged(void)
{
	int			rc;
	std::string	out;
	json		j;
	std::string	err;

	use_closed_endpoint();
	out = run_cli({"inspect", MEMBRANE_RUNTIME_ID_NATIVE}, false, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_SUCCESS, "native inspect exits 0");
	TEST_ASSERT(contains(out, "Execution mode: embedded_native\n"
		"  Status: available\n\nCapabilities\n"), "native human block is "
		"exactly H1's (no Health/Endpoint/Version/Reason lines)");
	TEST_ASSERT(!contains(out, "Health:") && !contains(out, "Reason"),
		"no probe lines for an embedded runtime");
	TEST_ASSERT(membrane_runtime_inspect_json(MEMBRANE_RUNTIME_ID_NATIVE, &j,
		&err) && j["runtime"]["capabilities"]["kv_precision_control"]
		== "supported" && j["runtime"]["capabilities"]["concurrency_control"]
		== "partial", "native matrix unchanged");
	out = run_cli({"models", MEMBRANE_RUNTIME_ID_NATIVE}, true, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_CLI_ERROR
		&& contains(out, "membrane model list"), "native models are "
		"MEMBRANE's own registry, not a runtime inventory");
	out = run_cli({"models", MEMBRANE_RUNTIME_ID_VLLM}, true, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_CLI_ERROR && contains(out, "reserved"),
		"vllm is still reserved-only");
	run_cli({"model", "show", "ollama", "x"}, true, &rc);
	TEST_ASSERT(rc == MEMBRANE_EXIT_CLI_ERROR, "unknown model verb");
}

int	main(void)
{
	start_mock_server();
	test_allowlist();
	test_endpoint_parsing();
	test_unavailable_descriptor();
	test_unavailable_cli_has_no_socket_error();
	test_healthy_version();
	test_list_shows_version_when_reachable();
	test_models_parsed();
	test_models_human();
	test_malformed_version();
	test_version_timeout_is_bounded();
	test_malformed_models();
	test_model_inspect();
	test_cloud_refs_refused_without_request();
	test_capability_matrix();
	test_endpoint_override();
	test_read_only_and_no_inference();
	test_native_unchanged();
	stop_mock_server();
	printf("test_runtime_ollama: all tests passed\n");
	return (0);
}
