#ifndef MEMBRANE_WINDOWS_TASK_H
# define MEMBRANE_WINDOWS_TASK_H

# include <string>

/*
 * Mega Phase D, PR D5: pure Windows Task Scheduler XML generation --
 * no filesystem access, no schtasks.exe invocation (that lives in
 * service_cmd.cpp, dispatched there via #ifdef _WIN32) -- testable
 * with plain string assertions, exactly mirroring systemd_unit.h/
 * launchd_unit.h's own split (those files' own top comments have the
 * reasoning).
 *
 * Task Scheduler is Windows's own per-user "startup task" mechanism --
 * the task's own explicit language ("Windows service/startup task")
 * allows either; a full Win32 Service (Service Control Manager,
 * ServiceMain dispatch table, a real service-hosting architecture
 * change to the binary itself) is a materially larger undertaking than
 * a scheduled task, which -- like systemd --user and launchd -- runs
 * under the calling user's own account with no elevated privileges of
 * any kind (Section 5's own "no root/no elevated capabilities" policy,
 * applied here as "no LocalSystem/elevated Task Scheduler principal").
 */

# define MEMBRANE_TASK_NAME		"MembraneServer"
# define MEMBRANE_TASK_MARKER	"Generated by `membrane service install` -- managed by MEMBRANE, safe to regenerate"

typedef struct s_membrane_task_options
{
	std::string	exec_path;	/* absolute path to the membrane binary */
	std::string	log_path;	/* stdout/stderr redirect target; defaults
								 * applied by the generator if empty */
}	membrane_task_options_t;

/* A Task Scheduler 1.2 XML document, real and schtasks.exe-loadable
 * (`schtasks /create /tn MembraneServer /xml <this> /f`). The task's
 * own Action runs via `cmd.exe /c` so real stdout/stderr redirection
 * to a log file is possible at all -- Task Scheduler itself has no
 * built-in output-capture the way launchd's StandardOutPath/
 * StandardErrorPath keys do, so `membrane service logs` (Windows path)
 * tails this same real file, the same real "no journal, tail a file"
 * approach docs/service.md's own launchd section already established.
 * LogonTrigger + Enabled=false-by-default RunAtLoad-equivalent: this
 * project's own no-auto-start-without-being-asked policy (matching
 * systemd_unit.h's no [Install] WantedBy-equivalent auto-start, and
 * launchd_unit.h's own RunAtLoad=false) is expressed here by NOT
 * registering any trigger that fires the task automatically --
 * `membrane service start` (a real `schtasks /run`) is the one,
 * explicit way this task ever actually starts. MultipleInstancesPolicy
 * IgnoreNew is Task Scheduler's own closest analog to a bounded
 * restart/re-entry policy (systemd's Restart=on-failure, launchd's
 * KeepAlive/ThrottleInterval have no direct Task Scheduler
 * equivalent -- disclosed, not claimed identical, in
 * docs/windows-support.md). */
std::string	membrane_generate_task_xml(const membrane_task_options_t &opts);

/* Task Scheduler tasks are identified by name (MEMBRANE_TASK_NAME), not
 * a filesystem path the way systemd units/launchd plists are -- this
 * function exists for symmetry with membrane_unit_file_path()/
 * membrane_launchd_plist_path() (a stable, single name for
 * `schtasks /query|/run|/end|/delete /tn ...` to address), not a real
 * path. MEMBRANE_TASK_NAME_OVERRIDE overrides it outright, the same
 * test-hook convention MEMBRANE_SYSTEMD_USER_DIR/
 * MEMBRANE_LAUNCHD_USER_DIR already established (tests/CI never touch
 * a real user's own scheduled tasks under the real default name). */
std::string	membrane_task_name(void);

/* True iff `xml` (the real, live `schtasks /query /tn ... /xml`
 * output) carries MEMBRANE_TASK_MARKER inside its own <Description>
 * element -- used to refuse overwriting a same-named task this project
 * did not create, same refuse-to-overwrite policy as systemd_unit.h's
 * membrane_unit_is_membrane_managed()/launchd_unit.h's
 * membrane_launchd_plist_is_membrane_managed(). */
bool	membrane_task_xml_is_membrane_managed(const std::string &xml);

# ifdef _WIN32
/* A real, first-attempt Windows CI finding: `schtasks /create /xml`
 * genuinely requires the XML file on disk to actually BE UTF-16
 * (Task Scheduler's own documented preference for its XML import) --
 * writing membrane_generate_task_xml()'s own plain UTF-8 std::string
 * bytes directly (matching its own `encoding="UTF-16"` declaration in
 * name only, not in the real bytes) failed with a real schtasks.exe
 * error: "ERROR: unable to switch the encoding". Converts real UTF-8
 * text to real UTF-16LE bytes (via MultiByteToWideChar(), prefixed
 * with a real byte-order-mark) -- the caller (service_cmd.cpp's own
 * Windows install path) writes the RESULT of this function to the
 * temp XML file, not membrane_generate_task_xml()'s own return value
 * directly. Windows-only (the pure generator above needs no such
 * step on any other platform, which never uses Task Scheduler at
 * all). */
std::string	membrane_task_xml_to_utf16le_bytes(const std::string &utf8_xml);
# endif

#endif
