#!/usr/bin/env bash
#
# scripts/prepare-release.sh -- pre-release checklist for MEMBRANE.
#
# Runs, in order:
#   1. clean-tree check (git status, excluding the pre-existing
#      third_party/llama.cpp dirty submodule noted throughout this
#      project's history)
#   2. test suite (Release build + ctest) -- skipped under --dry-run
#   3. scripts/verify-results.py (headline-claim vs. artifact checks)
#   4. benchmarks/MANIFEST.json freshness (--check, never silently
#      regenerated by this script -- a release script should not mutate
#      committed artifacts on its own)
#   5. docs link checker (every relative markdown link resolves to a
#      real file)
#   6. large-file check (tracked files over 50 MiB, flagged for manual
#      review -- not an automatic failure, since a real large artifact
#      may be intentional)
#   7. license/release-metadata file check
#   8. release summary
#
# Usage: scripts/prepare-release.sh [--dry-run]
#   --dry-run   skip the (multi-minute) build+ctest step; run every
#               other check in read-only mode. Use this for a quick
#               "is this ready" signal; run without --dry-run before
#               actually tagging a release.
#
# Exit code: 0 if every check passed (or was skipped under --dry-run
# with no other failures); non-zero otherwise, with each failing check
# named.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

DRY_RUN=0
for arg in "$@"; do
	case "$arg" in
	--dry-run) DRY_RUN=1 ;;
	*)
		echo "prepare-release.sh: unknown argument: $arg" >&2
		exit 2
		;;
	esac
done

CHECKS_TOTAL=0
CHECKS_FAILED=0
FAIL_NAMES=()

pass() { echo "[PASS] $1"; CHECKS_TOTAL=$((CHECKS_TOTAL + 1)); }
fail() { echo "[FAIL] $1"; CHECKS_TOTAL=$((CHECKS_TOTAL + 1)); CHECKS_FAILED=$((CHECKS_FAILED + 1)); FAIL_NAMES+=("$1"); }
skip() { echo "[SKIP] $1"; }

echo "== 1/8: clean working tree =="
DIRTY="$(git status --porcelain | grep -v '^ M third_party/llama\.cpp$' || true)"
if [ -z "$DIRTY" ]; then
	pass "working tree clean (excluding the known pre-existing third_party/llama.cpp submodule state)"
else
	fail "working tree has uncommitted changes:
$DIRTY"
fi

echo
echo "== 2/8: test suite =="
if [ "$DRY_RUN" -eq 1 ]; then
	skip "test suite (--dry-run) -- would run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build -j && ctest --test-dir build --output-on-failure"
else
	if cmake -S "$REPO_ROOT" -B "$REPO_ROOT/build" -DCMAKE_BUILD_TYPE=Release >/tmp/prepare-release-configure.log 2>&1 &&
		cmake --build "$REPO_ROOT/build" -j >/tmp/prepare-release-build.log 2>&1; then
		if ctest --test-dir "$REPO_ROOT/build" --output-on-failure >/tmp/prepare-release-ctest.log 2>&1; then
			summary=$(grep -o '[0-9]*% tests passed.*' /tmp/prepare-release-ctest.log | tail -1)
			pass "test suite: ${summary:-see /tmp/prepare-release-ctest.log}"
		else
			fail "test suite: see /tmp/prepare-release-ctest.log"
		fi
	else
		fail "build failed, see /tmp/prepare-release-configure.log and /tmp/prepare-release-build.log"
	fi
fi

echo
echo "== 3/8: verify-results.py =="
if python3 "$REPO_ROOT/scripts/verify-results.py" >/tmp/prepare-release-verify.log 2>&1; then
	pass "verify-results.py: $(tail -1 /tmp/prepare-release-verify.log)"
else
	fail "verify-results.py: see /tmp/prepare-release-verify.log"
	cat /tmp/prepare-release-verify.log
fi

echo
echo "== 4/8: benchmarks/MANIFEST.json freshness =="
if python3 "$REPO_ROOT/scripts/generate-benchmark-manifest.py" --check >/tmp/prepare-release-manifest.log 2>&1; then
	pass "MANIFEST.json is up to date"
else
	fail "MANIFEST.json is stale -- run scripts/generate-benchmark-manifest.py; see /tmp/prepare-release-manifest.log"
fi

echo
echo "== 5/8: docs link checker =="
LINK_ERRORS=0
LINK_DETAILS=""
while IFS= read -r -d '' md_file; do
	md_dir="$(dirname "$md_file")"
	while IFS= read -r link; do
		target="${link%%#*}"
		[ -z "$target" ] && continue
		case "$target" in
		http://* | https://* | mailto:*) continue ;;
		esac
		resolved="$md_dir/$target"
		if [ ! -e "$resolved" ]; then
			LINK_ERRORS=$((LINK_ERRORS + 1))
			LINK_DETAILS="$LINK_DETAILS
  $md_file -> $target (resolved: $resolved)"
		fi
	done < <(grep -oE '\]\(([^:)]+)\)' "$md_file" | sed -E 's/^\]\((.*)\)$/\1/')
done < <(find "$REPO_ROOT" -name "*.md" -not -path "*/third_party/*" -not -path "*/build*/*" -not -path "*/demo-output/*" -print0)

if [ "$LINK_ERRORS" -eq 0 ]; then
	pass "docs link checker: all relative markdown links resolve"
else
	fail "docs link checker: $LINK_ERRORS broken link(s):$LINK_DETAILS"
fi

echo
echo "== 6/8: large-file check (tracked files > 50 MiB) =="
LARGE_FILES=""
while IFS= read -r f; do
	[ -f "$f" ] || continue
	size=$(stat -c%s "$f" 2>/dev/null || stat -f%z "$f" 2>/dev/null || echo 0)
	if [ "$size" -gt $((50 * 1024 * 1024)) ]; then
		LARGE_FILES="$LARGE_FILES
  $f ($((size / 1024 / 1024)) MiB)"
	fi
done < <(git ls-files)
if [ -z "$LARGE_FILES" ]; then
	pass "no tracked file exceeds 50 MiB"
else
	echo "[WARN] large tracked file(s) found, review before pushing (not an automatic failure):$LARGE_FILES"
fi

echo
echo "== 7/8: release metadata files present =="
MISSING_META=""
for f in LICENSE CITATION.cff CHANGELOG.md SECURITY.md CONTRIBUTING.md CODE_OF_CONDUCT.md SUPPORT.md README.md; do
	[ -f "$REPO_ROOT/$f" ] || MISSING_META="$MISSING_META $f"
done
if [ -z "$MISSING_META" ]; then
	pass "all release metadata files present"
else
	fail "missing release metadata file(s):$MISSING_META"
fi

echo
echo "== 8/8: release summary =="
echo "Checks: $((CHECKS_TOTAL - CHECKS_FAILED))/$CHECKS_TOTAL passed$([ "$DRY_RUN" -eq 1 ] && echo ' (--dry-run: test suite skipped)')"
GIT_COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
echo "Commit: $GIT_COMMIT"
echo "Manifest artifacts: $(python3 -c "import json; print(json.load(open('$REPO_ROOT/benchmarks/MANIFEST.json'))['artifact_count'])" 2>/dev/null || echo unknown)"

if [ "$CHECKS_FAILED" -gt 0 ]; then
	echo
	echo "prepare-release.sh: $CHECKS_FAILED check(s) failed: ${FAIL_NAMES[*]}" >&2
	exit 1
fi

echo
echo "prepare-release.sh: all checks passed."
exit 0
